version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"
        exclude-patterns:
          # These dependencies are responsible for code generation. Updating them
          # likely also requires regenerating code, so it’s a good idea to update
          # them separately from other dev dependencies.
          - "@hey-api/*"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"
        exclude-patterns:
          # Maintain option to merge typeshed packages separately, to ensure they
          # are in sync with the respective package.
          - "types-*"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
