version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 50
    groups:
      dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"
        exclude-patterns:
          # These dependencies are responsible for code generation. Updating them
          # likely also requires regenerating code, so it’s a good idea to update
          # them separately from other dev dependencies.
          - "@hey-api/*"
      minor-patch:
        applies-to: "version-updates"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 50
    groups:
      dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"
      minor-patch:
        applies-to: "version-updates"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"
