volumes:
  meilisearch_data: {}
  caddy_data: {}
  caddy_config: {}

networks:
  # This network is used to limit network access of the `chromium` service
  # to just the `backend` and `frontend` services, disabling internet access.
  chromium:
    driver: bridge
    internal: true

services:
  frontend:
    image: "ghcr.io/howtheyvote/fragments-poc-frontend:main"
    depends_on:
      - backend
    networks:
      - "default"
      - "chromium"
    expose:
      - "8000"
    restart: "unless-stopped"
    environment:
      HTV_FRONTEND_PUBLIC_URL: "${HTV_FRONTEND_PUBLIC_URL}"
      HTV_BACKEND_PRIVATE_URL: "http://backend:5000"
      HTV_BACKEND_PUBLIC_URL: "${HTV_BACKEND_PUBLIC_URL}"

  backend:
    image: "ghcr.io/howtheyvote/fragments-poc-backend:main"
    depends_on:
      - meilisearch
      - chromium
    networks:
      - "default"
      - "chromium"
    ports:
      # Make Prometheus metrics available on host machine
      - "5000:5000"
    volumes:
      - "./storage/database:/howtheyvote/database"
      - "./storage/files:/howtheyvote/files"
    restart: "unless-stopped"
    environment:
      HTV_BACKEND_PUBLIC_URL: "${HTV_BACKEND_PUBLIC_URL}"
      HTV_FRONTEND_PUBLIC_URL: "${HTV_FRONTEND_PUBLIC_URL}"
      HTV_FRONTEND_PRIVATE_URL: "http://frontend:8000"
      MEILI_URL: "http://meilisearch:7700"
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"

  worker:
    image: "ghcr.io/howtheyvote/fragments-poc-backend:main"
    command: "htv worker"
    depends_on:
      - meilisearch
      - chromium
    ports:
      # Make Prometheus metrics available on host machine
      - "3000:3000"
    volumes:
      - "./storage/database:/howtheyvote/database"
      - "./storage/files:/howtheyvote/files"
    restart: "unless-stopped"
    environment:
      HTV_BACKEND_PUBLIC_URL: "${HTV_BACKEND_PUBLIC_URL}"
      HTV_FRONTEND_PUBLIC_URL: "${HTV_FRONTEND_PUBLIC_URL}"
      MEILI_URL: "http://meilisearch:7700"
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"

  meilisearch:
    image: "getmeili/meilisearch:v1.3.1"
    expose:
      - "7700"
    volumes:
      - "meilisearch_data:/meili_data"
    restart: "unless-stopped"
    environment:
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"

  caddy:
    image: "caddy:2.7.6-alpine"
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"
      - "./caddy:/etc/caddy"
      - "./storage/files:/howtheyvote/files"
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    environment:
      CADDY_SITE_ADDRESS: "${CADDY_SITE_ADDRESS}"

  chromium:
    image: "chromedp/headless-shell:125.0.6368.2"
    command:
      - "--disable-gpu"
      - "--remote-allow-origins=*"
      - "--hide-scrollbars"
    networks:
      - "chromium"
    expose:
      - "9222"
