volumes:
  caddy_data: {}
  caddy_config: {}

networks:
  # This network is used to limit network access of the `chromium` service
  # to just the `backend` and `frontend` services, disabling internet access.
  chromium:
    driver: bridge
    internal: true

services:
  frontend:
    image: "ghcr.io/howtheyvote/howtheyvote-frontend:main"
    depends_on:
      - backend
    networks:
      - "default"
      - "chromium"
    expose:
      - "8000"
    restart: "unless-stopped"
    environment:
      HTV_FRONTEND_PUBLIC_URL: "${HTV_FRONTEND_PUBLIC_URL}"
      HTV_BACKEND_PRIVATE_URL: "http://backend:5000"
      HTV_BACKEND_PUBLIC_URL: "${HTV_BACKEND_PUBLIC_URL}"

  backend:
    image: "ghcr.io/howtheyvote/howtheyvote-backend:main"
    depends_on:
      - chromium
    networks:
      - "default"
      - "chromium"
    ports:
      # Make Prometheus metrics available on host machine
      - "5000:5000"
    volumes:
      - "./storage/database:/howtheyvote/database"
      - "./storage/files:/howtheyvote/files"
      - "./storage/index:/howtheyvote/index"
    restart: "unless-stopped"
    environment:
      HTV_BACKEND_PUBLIC_URL: "${HTV_BACKEND_PUBLIC_URL}"
      HTV_FRONTEND_PUBLIC_URL: "${HTV_FRONTEND_PUBLIC_URL}"
      HTV_FRONTEND_PRIVATE_URL: "http://frontend:8000"
      PUSHOVER_API_TOKEN: "${PUSHOVER_API_TOKEN}"
      PUSHOVER_USER_KEY: "${PUSHOVER_USER_KEY}"

  worker:
    image: "ghcr.io/howtheyvote/howtheyvote-backend:main"
    command: "htv worker"
    depends_on:
      - chromium
    networks:
      - "default"
      - "chromium"
    ports:
      # Make Prometheus metrics available on host machine
      - "3000:3000"
    volumes:
      - "./storage/database:/howtheyvote/database"
      - "./storage/files:/howtheyvote/files"
      - "./storage/index:/howtheyvote/index"
    restart: "unless-stopped"
    environment:
      HTV_BACKEND_PUBLIC_URL: "${HTV_BACKEND_PUBLIC_URL}"
      HTV_FRONTEND_PUBLIC_URL: "${HTV_FRONTEND_PUBLIC_URL}"
      HTV_FRONTEND_PRIVATE_URL: "http://frontend:8000"
      PUSHOVER_API_TOKEN: "${PUSHOVER_API_TOKEN}"
      PUSHOVER_USER_KEY: "${PUSHOVER_USER_KEY}"

  caddy:
    image: "caddy:2.10.0-alpine"
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"
      - "./caddy:/etc/caddy"
      - "./storage/files:/howtheyvote/files"
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    environment:
      CADDY_SITE_ADDRESS: "${CADDY_SITE_ADDRESS}"

  chromium:
    image: "chromedp/headless-shell:139.0.7258.66"
    command:
      - "--disable-gpu"
      - "--remote-allow-origins=*"
      - "--hide-scrollbars"
    networks:
      - "chromium"
    expose:
      - "9222"
