[project]
requires-python = ">=3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "howtheyvote"
version = "0.1.0"
description = ""
authors = ["Till Prochaska <mail@tillprochaska.de>"]

[tool.poetry.scripts]
htv = "howtheyvote.cli:cli"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
requests = "^2.32.2"
unidecode = "^1.3.4"
beautifulsoup4 = "^4.11.1"
lxml = "^4.9.1"
alembic = "^1.9.3"
click = "^8.1.3"
structlog = "^22.3.0"
flask = "^2.2.3"
cachetools = "^5.3.0"
meilisearch = "^0.28.2"
pillow = "^10.0.0"
gunicorn = "^22.0.0"
apispec = "^6.3.0"
apispec-webframeworks = "^0.5.2"
prometheus-client = "^0.17.1"
sqlalchemy = "^2.0.23"
schedule = "^1.2.1"
pytz = "^2024.1"
websocket-client = "^1.7.0"

[tool.poetry.group.dev.dependencies]
coverage = "^6.4"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
mypy = "^1.7.1"
ruff = "^0.1.8"
types-pillow = "^10.1.0.2"
types-requests = "^2.31.0.10"
types-beautifulsoup4 = "^4.12.0.7"
types-cachetools = "^5.3.0.7"
setuptools = "^69.0.2"
pytest-env = "^1.1.3"
responses = "^0.24.1"
time-machine = "^2.13.0"

[tool.ruff]
select = ["E", "F", "W", "I", "N", "B", "UP", "UP006"]
line-length = 95

[tool.ruff.per-file-ignores]
"tests/*" = ["E501"]
"__init__.py" = ["F401"]

[tool.mypy]
exclude = ["alembic", ".venv"]

[tool.pytest.ini_options]
env = [
    "D:HTV_BACKEND_DATABASE_URI=sqlite:////howtheyvote/database/database.test.sqlite3",
    "D:HTV_BACKEND_USERS_DATABASE_URI=sqlite:////howtheyvote/database/users.test.sqlite3",
    "HTV_BACKEND_PUBLIC_URL=https://example.org/api",
    "HTV_SEARCH_INDEX_PREFIX=test",
]
addopts = [
    "--import-mode=importlib",
]
