[project]
requires-python = ">=3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "howtheyvote"
version = "0.1.0"
description = ""
authors = ["Till Prochaska <mail@tillprochaska.de>"]

[tool.poetry.scripts]
htv = "howtheyvote.cli:cli"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
requests = "^2.32.3"
unidecode = "^1.3.8"
beautifulsoup4 = "^4.12.3"
lxml = "^5.2.2"
alembic = "^1.13.2"
click = "^8.1.3"
structlog = "^24.2.0"
flask = "^3.0.3"
cachetools = "^5.3.3"
meilisearch = "^0.31.3"
pillow = "^10.4.0"
gunicorn = "^22.0.0"
apispec = "^6.6.1"
apispec-webframeworks = "^1.1.0"
prometheus-client = "^0.20.0"
sqlalchemy = "^2.0.31"
schedule = "^1.2.2"
pytz = "^2024.1"
websocket-client = "^1.8.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.5"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
mypy = "^1.10.0"
ruff = "^0.4.8"
types-pillow = "^10.2.0.20240520"
types-requests = "^2.32.0.20240622"
types-beautifulsoup4 = "^4.12.0.20240511"
types-cachetools = "^5.3.0.7"
setuptools = "^70.0.0"
pytest-env = "^1.1.3"
responses = "^0.25.2"
time-machine = "^2.14.1"

[tool.ruff]
line-length = 95

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "B", "UP", "UP006"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["E501"]
"__init__.py" = ["F401"]

[tool.mypy]
exclude = ["alembic", ".venv"]

[tool.pytest.ini_options]
env = [
    "D:HTV_BACKEND_DATABASE_URI=sqlite:////howtheyvote/database/database.test.sqlite3",
    "D:HTV_BACKEND_USERS_DATABASE_URI=sqlite:////howtheyvote/database/users.test.sqlite3",
    "HTV_BACKEND_PUBLIC_URL=https://example.org/api",
    "HTV_SEARCH_INDEX_PREFIX=test",
]
addopts = [
    "--import-mode=importlib",
]
