name: Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-26.04-arm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build backend image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          platforms: linux/arm64
          load: true
          tags: backend
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check formatting
        run: docker run --rm backend make format-check

      - name: Run linter
        run: docker run --rm backend make lint

      - name: Run types
        run: docker run --rm backend make typecheck

      - name: Run tests
        run: docker run --rm --env HTV_BACKEND_DATABASE_URI=sqlite:// backend make test
