name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Xapian
        run: sudo apt-get -y -q install python3-xapian

      - name: Install poetry
        run: pipx install "poetry<2.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
          cache-dependency-path: "./backend/poetry.lock"

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: make format-check

      - name: Run linter
        run: make lint

      - name: Run types
        run: make typecheck

      - name: Run tests
        run: make test
        env:
          HTV_BACKEND_DATABASE_URI: "sqlite:///${{ github.workspace }}/storage/database/database.sqlite3"
          HTV_BACKEND_USERS_DATABASE_URI: "sqlite:///${{ github.workspace }}/storage/database/users.sqlite3"
          HTV_SEARCH_INDEX_DIR: "${{ github.workspace }}/storage/index"
