name: Update JSON data

on:
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 1 * *" # every month on the 1st at 0:00

jobs:
  update:
    runs-on: ubuntu-26.04-arm

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build backend image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          load: true
          tags: backend
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start Docker container
        run: |
          docker run \
          --name=data \
          --volume=./backend/howtheyvote/data:/howtheyvote/backend/howtheyvote/data \
          backend \
          sleep infinity

      - name: Update committees
        run: docker exec data htv dev load-committees

      - name: Update countries
        run: docker exec data htv dev load-countries

      - name: Update EuroVoc concepts
        run: docker exec data htv dev load-eurovoc

      - name: Update political groups
        run: docker exec data htv dev load-groups

      - name: Stop Docker container
        run: docker rm -f data

      - name: Send Pushover notification
        if: failure()
        run: |
          curl \
            --silent \
            --form-string "token=${{ secrets.PUSHOVER_API_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            --form-string "message=Failed updating JSON reference datasets" \
            --form-string "url_title=Workflow run" \
            --form-string "url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            https://api.pushover.net/1/messages.json

      - name: Check for changes
        id: changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git checkout -b "bot/update-json-data"
          git add .
          git commit -m "Update JSON reference datasets"
          git push --force-with-lease origin bot/update-json-data

      - name: Open pull request
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          pr_count=$(gh pr list --head=bot/update-json-data --state=open --json=id --jq=length)

          if [[ "$pr_count" -gt 0 ]]; then
            echo "A pull request already exists. Skipping creation."
          else
            gh pr create \
              --title "Update JSON data" \
              --body "This pull request was opened automatically." \
              --head "bot/update-json-data" \
              --base main
          fi
        env:
          GH_TOKEN: ${{ github.token }}
