name: Docker images

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
  pull_request: {}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - frontend
          - backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      # Required to build multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Automatically tags Docker images based on Git tags, branches etc.
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.image }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.image }}
          platforms: linux/arm64
          push: ${{ github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
